In [12]:
import numpy
# 如果你对ndarray进行操作，它是会对立面的每个元素都进行操作
# 如果值相等返回True 否则返回False
vector = numpy.array([5, 10, 15, 20])
vector == 10 

array([False,  True, False, False])

In [13]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [14]:
#布尔类型当索引 把返回的布尔值 当成ndarray的索引传进去 如果False不反回，True就可以取出值
vector = numpy.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])

[False  True False False]
[10]


In [15]:
# 二维矩阵里面的所有行，0,1列里面是否有25，就可以取出含有25的那一行的所有列，: 代表所有
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
second_column_25 = (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25, :])

[False  True False]
[[20 25 30]]


In [16]:
#一个值既等于10 又等于5 
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [17]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [18]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
# 可以把True的值进行赋值
print(vector)

[50 50 15 20]


In [19]:
matrix = numpy.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
second_column_25 = matrix[:,1] == 25
print(second_column_25)
matrix[second_column_25, 1] = 10
print(matrix)

[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [20]:
vector = numpy.array(["1", "2", "3"])
print(vector.dtype)
print(vector)
# astype 可以对它值类型的转换 转为 float类型
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [22]:
vector = numpy.array([5, 10, 15, 20])
vector.sum()

50

In [23]:
vector = numpy.array([5, 10, 15, 20])
vector.min()

5

In [25]:
# 指定维度 按行axis=1 列axis=0求和 
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(axis=1)

array([ 30,  75, 120])

In [26]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(axis=0)


array([60, 75, 90])

In [27]:
#replace nan value with 0
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",")
#print world_alcohol
is_value_empty = numpy.isnan(world_alcohol[:,4])
#print is_value_empty
world_alcohol[is_value_empty, 4] = '0'
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()
print(total_alcohol)
print(average_alcohol)

1137.78
1.140060120240481
